### ISSUE TITLE
Recognition of types.

### ISSUE THREAD

**Issue by Bzik** [dart-bridge/trestle#3]
In database i have someSchema.numeric('points') 
in DTO 
@Field()
double points;

If points, in database, are integer it doesn't cast it to double. That's why I cant use simple annotations and need to use data mapping :/

Also if string field contains value '1' it will be cast as integer not string.

**Comment by emilniklas** [comment]
Hello!

What database driver are you using? I can't find any place where I cast the type, so it probably lies in the driver implementation.

**Comment by Bzik** [comment]
I'm using PostgreSQL.

**Comment by emilniklas** [comment]
@Bzik I have looked this up, and Trestle actually never does anything to the types. This has to be from the PostgreSQL library itself. If a field is declared as floating number in the schema, then the queries should be returned parsed as such.

I would recommend you take this to https://github.com/xxgreg/dart_postgresql
