### ISSUE TITLE
ORM ignore unique()

### ISSUE THREAD

**Issue by zaharsk** [dart-bridge/trestle#6]
# Description

This code:

```
Future createUsersTable() async {
  await gateway.create(users.table, (Schema schema) {
    schema.id();
    schema.timestamps();
    schema.string('uid').unique().nullable(false);
    schema.string('tel').unique().nullable(false);
    schema.string('ls').unique().nullable(false);
    schema.string('password').nullable(false);
    schema.string('city').nullable(false);
  });
}
```

generate this SQL:
`CREATE TABLE "users" ("id" SERIAL PRIMARY KEY, "created_at" TIMESTAMP NOT NULL, "updated_at" TIMESTAMP NOT NULL, "uid" VARCHAR(255) NOT NULL, "tel" VARCHAR(255) NOT NULL, "ls" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "city" VARCHAR(255) NOT NULL);`
# Enviroment
## Server
- Ubuntu 16.04.1 LTS (Linux %domain_name% 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:41:41 UTC 2016 i686 i686 i686 GNU/Linux)
- PostgreSQL 9.5.4 on i686-pc-linux-gnu, compiled by gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413, 32-bit
## Client
- Windows 10 Pro x64 (MSYS_NT-10.0 %user_name% 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys)
- Dart SDK 1.19.0
- trestle-0.8.0

**Comment by emilniklas** [comment]
I fixed this and published 0.9.0! Simple bug. Thanks for reporting 🎉
